language: swift
rvm:
  2.6
xcode_workspace: NthKey.xcworkspace
xcode_scheme: NthKey
xcode_destination: platform=iOS Simulator,OS=14.2,name=iPhone 8
osx_image: xcode12.2

cache:
  ccache: true
  cocoapods: true
  directories:
     - /Users/travis/.rvm/

install:
  - gem install xcpretty
  - swift --version
  - brew install gnu-sed ccache cocoapods
  - export PATH="/usr/local/opt/ccache/libexec:$PATH"
  - pod install --verbose
