source: ./docs
theme: jekyll-theme-hacker
title: NthKey
tagline: Bitcoin multi-signature for iOs
author:
  twitter: nthKeyApp
logo: /assets/logo.png
twitter:
  creator: @provoost
  card: summary_large_image
