//
//  PSBT.swift
//  PSBT
//
//  Created by Sergey Vinogradov on 19.04.2021.
//  Copyright © 2021 Purple Dunes. Distributed under the MIT software
//  license, see the accompanying file LICENSE.md

import LibWally

#if DEBUG
extension PSBT {
    static var mock: PSBT {
        let psbt = """
                                cHNidP8BAH0CAAAAAfxHXu9fXH/SbBc7cjaK3cG6IlaNvbunN7e9CxXerzd3AQAAAAD9////AhAnAAAAAAAAFgAUaZdrsnwNQX20yqPTHICJS0iFVQLsXgEAAAAAACIAIO3qA4rNDPtVvtVx9UywD/F3cTXAqfOlTX1ySvBFJyl1AAAAAE8BBDWHzwShWGDXgAAAApanJsBeM8UFmSLGipe3Nzjcr1nvGuMNWOBVtmwoHONYAgj4llzdikooReVnpiilD9N9xVJQ3rV0TZZENpDgabe8FDoaF/EwAACAAQAAgAAAAIACAACATwEENYfPBKlUT3eAAAAC2i8MBsniuAbmeF4RMcHs8GYB7CN9NK58lWJstVkly5gDhILEGj3Ua5X3L7PUlOQxk4iOHuiugVkI9kIZugB/orcUUqQPNzAAAIABAACAAAAAgAIAAIAAAQEroIYBAAAAAAAiACA047AHmZSoHCeg2sdfACKTTidnugfxzZ8dtfwgfdal4QEFR1EhAtLh5IPD5yl+o7BgV4tLSmC26Q/MFeTQpBYa0tY2EigCIQLu7t59t/3XCbtj5b0mt+9YituFMNz9ou+yCzL5ULfjbFKuIgYC0uHkg8PnKX6jsGBXi0tKYLbpD8wV5NCkFhrS1jYSKAIcOhoX8TAAAIABAACAAAAAgAIAAIAAAAAAAAAAACIGAu7u3n23/dcJu2PlvSa371iK24Uw3P2i77ILMvlQt+NsHFKkDzcwAACAAQAAgAAAAIACAACAAAAAAAAAAAAAAAEBR1EhAgjJAeLiRxxIJhr2uZeYZ5F7tGhCzTKk3PEuGRiS7mJiIQNq9H72bsLFFeE0jw7Sb5tKar+UsiieoU4GqHt/5K/9vFKuIgICCMkB4uJHHEgmGva5l5hnkXu0aELNMqTc8S4ZGJLuYmIcUqQPNzAAAIABAACAAAAAgAIAAIABAAAAAAAAACICA2r0fvZuwsUV4TSPDtJvm0pqv5SyKJ6hTgaoe3/kr/28HDoaF/EwAACAAQAAgAAAAIACAACAAQAAAAAAAAAA
                                """
        return try! PSBT(psbt, .testnet)
    }
}
#endif
